covid19/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),  # Django后台
    path('', include('frontpage.urls')),
]

frontpage/urls.py
from django.urls import path
from . import views

app_name = 'frontpage'
urlpatterns = [
    path('', views.index, name='index'),  # 数据可视化
    path('query/', views.query, name='query'),  # 数据管理
    # 中国，全球疫情数据修改
    path('china_change/<int:data_id>/', views.china_change, name='china_change'),
    path('foreign_change/<int:data_id>/', views.foreign_change, name='foreign_change'),
]

frontpage/models.py
from django.db import models


class China(models.Model):
    """中国疫情数据"""
    date = models.CharField(max_length=20)
    area = models.CharField(max_length=40)
    newly = models.IntegerField()
    total = models.IntegerField()
    cure = models.IntegerField()
    dead = models.IntegerField()

    def __str__(self):
        """返回描述模型的字符串"""
        return f"{self.area}"


class ForeignArea(models.Model):
    """全球疫情数据"""
    date = models.CharField(max_length=20)
    country = models.CharField(max_length=40)
    newly = models.IntegerField()
    total = models.IntegerField()
    cure = models.IntegerField()
    dead = models.IntegerField()

    def __str__(self):
        """返回描述模型的字符串"""
        return f"{self.country}"

frontpage/forms.py
from django import forms
from .models import China, ForeignArea

"""创建表单(根据模型来创建)，其数据库迁移将由Django根据其指定的模型来自动完成"""


class ChinaForm(forms.ModelForm):
    class Meta:
        # 根据哪个模型来创建该表单
        model = China
        # 该表单类中包含的字段，"__all__"表示全部字段
        fields = '__all__'
        # 设置各字段在表单页面中生成的标签
        labels = {'date': '日期', 'area': '省份', 'newly': '新增确诊', 'total': '累计确诊', 'cure': '累计治愈', 'dead': '累计死亡'}


class ForeignAreaForm(forms.ModelForm):
    class Meta:
        model = ForeignArea
        fields = '__all__'
        labels = {'date': '日期', 'country': '国家', 'newly': '新增确诊', 'total': '累计确诊', 'cure': '累计治愈', 'dead': '累计死亡'}

frontpage/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import China, ForeignArea
from .forms import ChinaForm, ForeignAreaForm
from django.contrib.auth.decorators import login_required
from jinja2 import Environment, FileSystemLoader
from pyecharts.globals import CurrentConfig
import pandas as pd
from pyecharts.charts import Map, Pie, WordCloud, Line, Page
from pyecharts.components import Table
from pyecharts import options as opts
import pymysql
import time
import datetime
import json
import re
import warnings

warnings.simplefilter('ignore', category=UserWarning)

CurrentConfig.GLOBAL_ENV = Environment(loader=FileSystemLoader("./frontpage/templates"))


@login_required
def china_change(request, data_id):
    """中国疫情数据修改"""
    china_data = China.objects.get(id=data_id)
    if request.method != 'POST':
        # 未提交数据：创建一个空表单，且使用旧条目内容填充表单
        form = ChinaForm(instance=china_data)
    else:
        # 对POST提交的数据进行处理：在旧条目(instance=china_data)上，覆盖上新条目的内容(data=request.POST)
        form = ChinaForm(instance=china_data, data=request.POST)
        if form.is_valid():
            # 用该表单对象来执行数据库的存储操作
            form.save()
            # 用户填入的表单数据存入数据库后，重定向页面至查询页
            return redirect('frontpage:query')
    # 显示空表单或指出表单数据无效
    context = {'china_data': china_data, 'form': form}
    # 调用新建条目页面的模板，并传入上下文字典
    return render(request, 'frontpage/china_change.html', context)


@login_required
def foreign_change(request, data_id):
    """全球疫情数据修改"""
    foreign_data = ForeignArea.objects.get(id=data_id)
    if request.method != 'POST':
        form = ForeignAreaForm(instance=foreign_data)
    else:
        form = ForeignAreaForm(instance=foreign_data, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('frontpage:query')
    context = {'foreign_data': foreign_data, 'form': form}
    return render(request, 'frontpage/foreign_change.html', context)


@login_required
def query(request):
    """查询数据"""
    if request.method != 'POST':
        return render(request, 'frontpage/query.html')
    else:
        data = dict(request.POST)
        area = data['area'][0]
        date = f"{data['year'][0]}-{data['month'][0]}-{data['day'][0]}"
        if area == '中国':
            datas = China.objects.filter(date=date).order_by('total').reverse()
        elif area == '全球':
            datas = ForeignArea.objects.filter(date=date).order_by('total').reverse()
        context = {'datas': datas, 'area': area, 'date': date}
        return render(request, 'frontpage/datas.html', context=context)


def index(request):
    """数据可视化主页"""
    
    """生成数据集"""
    # 连接数据库
    con = pymysql.connect(host='127.0.0.1', user='root', passwd='root123', db='百度疫情')

    t = time.time()  # 本地时间戳
    local_time = time.localtime(t)
    date = time.strftime('%Y-%m-%d', local_time)
    hour = time.strftime('%H', local_time)
    if int(hour) < 10:  # 若此刻处于今日的10点钟前，则将日期推前10小时
        date = time.strftime('%Y-%m-%d', time.localtime(t-36000))
    # 获取绘制table_china，map，line，pie所需的今日数据
    df_china = pd.read_sql(f"select area,newly,total,cure,dead from frontpage_china where date = '{date}'",
                           con=con)  # 获取DataFrame
    china_data = df_china.values.tolist()  # DataFrame转换为列表：[['上海', 3241, 27078, 9288, 7], ...]
    china_data.sort(key=lambda x: x[1], reverse=True)

    # 获取绘制line_week所需的数据
    date_y, date_m, date_d = [int(x) for x in date.split('-')]
    begin = datetime.date(date_y, date_m, date_d)  # 创建datetime的日期对象
    week_date = [str(begin - datetime.timedelta(days=i)) for i in range(7)]  # 近一周的日期列表
    week_1, week_2, week_3, week_4, week_5, week_6, week_7 = week_date
    df_china_week = pd.read_sql(  # 中国近一周疫情DataFrame
        f"select area,newly,total,cure,dead from frontpage_china where date in ('{week_1}', '{week_2}', '{week_3}', '{week_4}', '{week_5}', '{week_6}', '{week_7}')"
        , con=con)  # 获取DataFrame
    week_data = df_china_week.values.tolist()  # DataFrame转换为列表
    area_list = [x[0] for x in week_data]  # 获取地区列表
    area_list = list(set(area_list))  # 去重
    china_week_data = list()
    for i in area_list:  # 倒序
        a = 0
        for j in week_data:
            if i == j[0]:
                a += j[1]
        china_week_data.append([i, a])
    china_week_data.sort(key=lambda x: x[1], reverse=True)
    
    # 获取绘制table_global，wordcloud所需的数据
    df_foreign = pd.read_sql(f"select country,newly,total,cure,dead from frontpage_foreignarea where date = '{date}'",
                             con=con)  # 通过sql语句获取到所需的DataFrame
    # [['美国', 44139, 82309113, 80166281, 1015441], ...]
    foreign_data = df_foreign.values.tolist()  # DataFrame转换为列表
    
    def line_week():
        """周折线图数据集： [['上海', 5661], ...]"""
        line_week = (
            Line(
                init_opts=opts.InitOpts(
                    width='700px',
                    height='400px',  # 图表的宽与高
                )
            )
            .add_xaxis(xaxis_data=[x[0] for x in china_week_data])  # x轴数据集
            .add_yaxis(
                '本周内的新增确诊',  # 数据集名
                [x[1] for x in china_week_data],  # y轴数据集
            )
            .set_global_opts(
                title_opts=opts.TitleOpts(
                    title='周确诊折线图',  # 标题
                    pos_right='90',  # 标题离画布左边，与顶边的相对距离
                    pos_top='40',  # 置顶位置
                    title_textstyle_opts=opts.TextStyleOpts(
                        font_size=24,  # 标题字号
                    ),
                ),
                legend_opts=opts.LegendOpts(is_show=False),  # 是否显示图例，默认为True
                xaxis_opts=opts.AxisOpts(type_='category'),  # x轴数据类型
                datazoom_opts=opts.DataZoomOpts(
                    is_show=True,  # 显示滑块
                    range_start=0,  # 滑块的起始范围(0-100，表示0%-100%)
                    range_end=30,
                )
            )
        )
        return line_week
    
    def wordcloud():
        """全球词云图"""
        wordcloud_data = [[x[0], x[2]] for x in foreign_data]
        wordcloud = (
            WordCloud(
                init_opts=opts.InitOpts(
                    width='600px',
                    height='360px',  # 图表的宽与高
                )
            )
            .add(
                '',
                wordcloud_data,  # 词云数据集
                word_size_range=[10, 150],  # 设置词云中文字的最小与最大尺寸
                textstyle_opts=opts.TextStyleOpts(font_family='cursive'),  # 设置字体
            )
            .set_global_opts(
                title_opts=opts.TitleOpts(
                    title='',  # 标题
                    pos_left='500',  # 标题离画布左边，与顶边的相对距离
                    title_textstyle_opts=opts.TextStyleOpts(
                        font_size=28,  # 标题字号
                    ),
                )
            )
        )
        return wordcloud
    
    def table_global():
        """全球各国的当日数据表格"""
        headers = ['国家', '新增确诊', '累计确诊', '累计治愈', '累计死亡']
        attributes = {"class": "fl-table"}
        table_global = (
            Table()
            .add(headers, foreign_data, attributes)
            .set_global_opts(title_opts=opts.ComponentTitleOpts(
                title='今日疫情数据：全球'),
            )
        )
        return table_global
    
    def table_china():
        """中国各省的当日数据表格"""
        headers = ['各省份/ 直辖市/ 自治区', '新增确诊', '新增无症状', '累计确诊', '风险地区']
        attributes = {"class": "fl-table"}
        table_china = (
            Table()
            .add(headers, china_data, attributes)
            .set_global_opts(title_opts=opts.ComponentTitleOpts(
                title='今日疫情数据：中国'),
            )
        )
        return table_china
    
    def pie():
        """饼图数据集(前九名与其他)"""
        pie_data = [[x[0], x[3]] for x in china_data]  # china_data(旧)：[['上海', 新增3241, 累计27078, 治愈9288, 死亡7], ...]
        pie_data.sort(key=lambda x: x[1], reverse=True)
        pie_9 = pie_data[:9]
        pie_other = ['其它省份', sum([x[1] for x in pie_data[9:]])]
        pie_9.append(pie_other)
        pie = (
            Pie(
                init_opts=opts.InitOpts(
                    width='600px',
                    height='300px',  # 图表的宽与高
                )
            )
            .add(  # 饼图以二维列表作为数据集，其中的每个列表包含2个元素，图例默认为“x”的各元素
                '累计确诊',  # 数据集名
                pie_9,  # 数据集
                radius=['10%', '75%'],
            )
            .set_global_opts(
                title_opts=opts.TitleOpts(
                    title='中国各省饼图',  # 标题
                    title_textstyle_opts=opts.TextStyleOpts(
                        font_size=24,  # 标题字号
                    ),
                ),
                legend_opts=opts.LegendOpts(orient='vertical', pos_top='12%', pos_left='0%'),  # 图例设置
                tooltip_opts=opts.TooltipOpts(formatter="{a}：{c}")  # 格式化浮窗：{a} 数据集名，{b} x值，{c} y值
            )
            .set_series_opts(label_opts=opts.LabelOpts(is_show=True))  # 图形标签字符的设置
        )
        return pie
    
    def line():
        """日折线图数据集(数据源是按新增确诊数降序排列的)： [['上海', 3241], ...]"""
        line_data = [[x[0], x[1]] for x in china_data]  # china_data(旧)：[['上海', 新增3241, 累计27078, 治愈9288, 死亡7], ...]
        line = (
            Line(
                init_opts=opts.InitOpts(
                    width='700px',
                    height='400px',  # 图表的宽与高
                )
            )
            .add_xaxis(xaxis_data=[x[0] for x in line_data])  # x轴数据集
            .add_yaxis(
                '新增确诊',  # 数据集名
                [x[1] for x in line_data],  # y轴数据集
            )
            .set_global_opts(
                title_opts=opts.TitleOpts(
                    title='日确诊折线图',  # 标题
                    pos_right='90',  # 标题离画布左边，与顶边的相对距离
                    pos_top='40',  # 置顶位置
                    title_textstyle_opts=opts.TextStyleOpts(
                        font_size=24,  # 标题字号
                    ),
                ),
                legend_opts=opts.LegendOpts(is_show=False),  # 是否显示图例，默认为True

frontpage/templates/frontpage/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Covid-19</title>
    <!--pyecharts渲染页面所需的js文件-->
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts-wordcloud.min.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/maps/china.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/jquery.min.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://assets.pyecharts.org/assets/ResizeSensor.js"></script>
    <link rel="stylesheet"  href="https://assets.pyecharts.org/assets/jquery-ui.css">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <!--navbar-brand文本更大号点-->
        <button class="btn btn-danger">
          <a style="font-size:18px; color:rgb(255, 255, 255)" href="{% url 'frontpage:index' %}">数据可视化</a>
        </button>
        <!--div(division分隔)标签开启了导航栏的一个新区域(应用样式或行为规则时，是分区域的)。其定义的样式与行为会仅作用于该标签的内部。
        这里设定了当屏幕或窗口太小时，从按钮中展开的导航栏的样式-->
        <!--collapse navbar-collapse响应式折叠类-->
        <div class="collapse navbar-collapse">
            <!--ml-auto(margin-left-automatic自动设定左边空白的间距)-->
            <ul class="navbar-nav ml-auto">
                <!--判断客户是否已登录。每个模板都可以使用user变量，is_authenticated返回布尔值，以判断是否登录-->
                {% if user.is_authenticated %}
                    <button class="btn btn-info">
                      <a style="font-size:18px; color:rgb(255, 255, 255)" href="{% url 'frontpage:query' %}">数据库管理</a>
                    </button>
                {% else %}
                    <button class="btn btn-info">
                        <a class="nav-link" href="http://127.0.0.1:8000/admin">登录</a>
                    </button>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!--main标签用于定义页面主体的最重要部分，container布局容器(两侧留白)，role(用于定义aria元素，主要是供残疾人使用)-->
    <main class="container">
        <!--content块用于添加页面的主体内容-->
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

frontpage/templates/frontpage/china_change.html
{% extends 'frontpage/base.html' %}
{% load bootstrap4 %}
{% block content %}

<span style="font-size:32px">数据修改：</span>
<span style="font-size:24px">{{ china_data.area }} {{ china_data.date }}</span><hr>
<form action="{% url 'frontpage:china_change' china_data.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="提交" class="btn btn-primary">执行修改</button>
    {% endbuttons %}
</form>

{% block data_list %}{% endblock data_list %}

{% endblock content %}

frontpage/templates/frontpage/datas.html
{% extends 'frontpage/query.html' %}
{% block data_list %}

  <main class="container" style="margin-top: 30px;">
    <div class="col-md-11 offset-md-1">
      <div class="col-md-12">
        <h3 class="pb-3 mb-4 blog-post-title border-bottom">
          {{ area }}： {{ date }}
        </h3>
        <div class="row">
          {% if area == '中国' %}
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">地区</span>
            </div>
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">新增确诊</span>
            </div>
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">新增无症状</span>
            </div>
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">累计确诊</span>
            </div>
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">风险地区</span>
            </div>
          {% else %}
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">地区</span>
            </div>
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">新增确诊</span>
            </div>
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">累计确诊</span>
            </div>
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">累计治愈</span>
            </div>
            <div class="col-md-2">
              <span style="font-size:20px; font-weight:bold">累计死亡</span>
            </div>
          {% endif %}
        </div><hr>
          <!--遍历主题实例，topics为视窗函数传入的上下文字典中的键名-->
          {% for data in datas %}
            <article class="blog-post">
                <h4 class="blog-post-title">
                  <div class="row">
                    <div class="col-md-2">
                      <a href="#">{{ data }}</a>
                    </div>
                  {% if area == '中国' %}
                    <div class="col-md-2">
                      <a href="#">{{ data.newly }}</a>
                    </div>
                    <div class="col-md-2">
                      <a href="#">{{ data.total }}</a>
                    </div>
                    <div class="col-md-2">
                      <a href="#">{{ data.cure }}</a>
                    </div>
                    <div class="col-md-2">
                      <a href="#">{{ data.dead }}</a>
                    </div>
                  {% else %}
                    <div class="col-md-2">
                      <a href="#">{{ data.newly }}</a>
                    </div>
                    <div class="col-md-2">
                      <a href="#">{{ data.total }}</a>
                    </div>
                    <div class="col-md-2">
                      <a href="#">{{ data.cure }}</a>
                    </div>
                    <div class="col-md-2">
                      <a href="#">{{ data.dead }}</a>
                    </div>
                  {% endif %}
                  {% if area == '中国' %}
                    <div class=" col-md-2">
                        <a href="{% url 'frontpage:china_change' data.id %}" class="btn btn-info"> 修 改 </a>
                    </div>
                  {% else %}
                    <div class=" col-md-2">
                        <a href="{% url 'frontpage:foreign_change' data.id %}" class="btn btn-info"> 修 改 </a>
                    </div>
                  {% endif %}
                  </div>
                </h4>
              <hr>
            </article>
          {% empty %}  <!--如果循环为空的话-->
            <li><h5>未查询到与条件相符的本地数据。</h5></li>
          {% endfor %}  <!--结束循环-->
      </div>
    </div>
  </main>

  <footer class="blog-footer">
    <p class="text-right"><a href="#">返回顶部</a></p>
  </footer>

{% endblock data_list %}

frontpage/templates/frontpage/foreign_change.html
{% extends 'frontpage/base.html' %}
{% load bootstrap4 %}
{% block content %}

<span style="font-size:32px">数据修改：</span>
<span style="font-size:24px">{{ foreign_data.country }} {{ foreign_data.date }}</span><hr>
<form action="{% url 'frontpage:foreign_change' foreign_data.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="提交" class="btn btn-primary">执行修改</button>
    {% endbuttons %}
</form>

{% block data_list %}{% endblock data_list %}

{% endblock content %}

frontpage/templates/frontpage/index.html
{% extends 'frontpage/base.html' %}
{% block content %}

  <div>{{ chart|safe }}</div>

{% endblock content %}

frontpage/templates/frontpage/query.html
{% extends 'frontpage/base.html' %}
{% block content %}

  <!--表单标签，其中action会告诉服务器将提交的数据发送到哪，提交方式为post(默认为get)-->
  <form action="{% url 'frontpage:query' %}" class="container container-small" method="post">
      <!--row用于将内部元素按一整行来布局，避免了2侧的留白-->
      <div class="row">
          <div class="col-md-3 offset-md-2">
              <div class="row">
                  <div class="col-md-6">  <!--appearance: none 去掉倒三角-->
                      <select name="area" class="btn btn-info form-control" style="appearance: none">
                        <option>中国</option>
                        <option>全球</option>
                      </select>
                  </div>
                  <div class="col-md-6">
                      <select name="year" class="btn btn-info form-control" style="appearance: none">
                        <option>2022</option>
                      </select>
                  </div>
              </div>
          </div>
          <div class="col-md-5">
              <div class="row">
                  <div class="col-md-4">
                      <input type="text" name="month" class="form-control" style="text-align:center; width: 135px;" placeholder="月">
                  </div>
                  <div class="col-md-4">
                      <input type="text" name="day" class="form-control" style="text-align:center; width: 135px;" placeholder="日">
                  </div>
                  <div class="col-md-2">
                    <input type="submit" class="btn btn-primary btn-sm" style="font-size:18px;" value=" 按日期查询 ">
                  </div>
              </div>
          </div>
      </div>
  </form>

{% block data_list %}{% endblock data_list %}

{% endblock content %}